export {default as Navbar} from './navbar'
export {default as Main} from './main'
export {default as Login} from './login'
export {default as Register} from './register'
export {default as Footer} from './footer'
export {default as Products} from './products'